apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:It2toiFvOKuWZSYb2dT/KlefmLchP8zi7zrnw4O2IeXQcU0G,iv:wuST7WKzR2mrVW++YblAxgUWZWE+ShJUp4ZdacHvUeI=,tag:tSDGjxj5dViHFUUR0bZr8g==,type:str]
    credentials.json: ENC[AES256_GCM,data:vusq7Gk7Wj5Pwy0YroDSvybYyDYJKICpzmfumK+bcHRR+Jyv207oE8CPjoKd6aBEjjbLpPBiJUW0RMMPpEBUcuNTVJwm8wv6WGazK1gQaL+jM2htgAyBxJNcCs+lBllVKa6AvNAkQZrVM7I8FkmtrgbUF/mNmQ449i+fH1r1CNvr+d06xrvRGlQw6WYMUCxHjkA5ouqCTI8516A4aZi/pzUsz+ETy/xQcqOdgv8tDg==,iv:qBFoIwtmS0ytNGdMcXStqEQoeq/izhC721c/RQwaYoo=,tag:th9imPjrqzv/GETO7PDBQQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1pkmjvv23yp3z304zhnp5308659krcqpkl9rxu82n84mp7f9ts4mql0znjy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCcVJqV1pDbjRWMHhXMDNB
            ZVM1TnJFaFI1QjF6WEk0Sm1DYVFyZjFDQWxzCnpYQUpXWG1DV1BDSHo4NVk3N2Zj
            OXQvMlJrRExHOHI5bENYNkhENk5kV0EKLS0tIDQrMG5XVGJXM3pUU2JFL1BSOElK
            UXpGUGhkY3Bqd2FHWll1UitndytrUHcKhR5jot+7CRjYydEhyLopiItIRhU90E98
            BdXnAFtdUYt3+hkIHG2E3UbWBl8I+PWSCZTSFSpXlqpGcreGPeMkjA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-07-25T08:52:47Z"
    mac: ENC[AES256_GCM,data:4F1AUWUKoL7C0EjzAxvCj9YDYoE/F2pjgXAnUOprer78rbycmQhQ4JpwJSqwF1lLmMCHFmmijZT5L9UdxBkzpoCB49x3vZQV0i2cXVcBRroyToWMP+x3h5EPAQ7Gt4CVYEHObWVT7MC6fFfRaHZcOcldu47QDIgIMT4SZWrnK48=,iv:Tt5YZPEDV0Di328evxtIeFxc/orIECSWhvii+1IXwdg=,tag:CCSJYX4RWZ7zI3apYLplhA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
