apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:GS/bAH9cNFxvK0NLN94rWRToQI+pfoz4Y9GXl9+3A2E=,iv:xh2V0F0WfNPMgnDjtBTegPYl58KyVhuLhSEbpyirYq0=,tag:wrllRbAUDp2omcvLAN/xeQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1pkmjvv23yp3z304zhnp5308659krcqpkl9rxu82n84mp7f9ts4mql0znjy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkWi9LdVRUODJXTHhWcS9D
            cEE2VXgvUmNaaC9QS3BmbW9jclNKQWRzaDJvCmd3bDVjWUxSaFFEaTBQRkFDL3Ni
            S2Z6K0swOFZHcWlXdnJKOTQ3MGNSa3MKLS0tIEVveE9Lbyt4MlQxMkE0K3dFeWNL
            di9KR2ZIQWhCampSMXF6MHNmYWVnK2cKuqQPUfftAlcQGLBthCWP8Iel3YId95hJ
            EuYavRphR7h5SQlN7g+40UCGb6ZFC1xs28rZoI5JYL3epdgWhINLJQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-07-25T08:52:47Z"
    mac: ENC[AES256_GCM,data:Qx2hab8mIn2HflJLdV24HGp5GwxZkTcJU75p0q+zHfgE6COilnMLBGEOZOgLemiwrjb/CS/1rAfBygjVXbKGok/985BvUwca/TXwA/u8BaxQ5xdjbH3c+DyVjnq9cxPJvNyh1KwhZjjtmtS1l3HiRxMgstsstpAIEYMbYUu9PYM=,iv:+xVbVWhikcoMGRqsCn7SnLQgAelZ9FAsDgua8zZn5Ng=,tag:M8IDnNTZITbsAyXjsZwFZg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
